### ISSUE TITLE
Script reinstalls workspace

### ISSUE THREAD

**Issue by Vibrane** [mikepurvis/ros-install-osx#123]
Your script seems to reinstall the workspace everytime I call ./install

I need to apply patches such as to the one in rostime, but I do not know how to do that if it reinstalls the ros distro everytime. 

I am very new at this. Sorry if this is stupid.

**Comment by mikepurvis** [comment]
No worries at all, nothing is stupid!

The script is very linear, so you shouldn't feel tied to running it in its entirety each time— if you apply patches to the source, just go into the workspace and manually re-run `catkin build`.

**Comment by Vibrane** [comment]
Oh okay, thanks !!!
