### ISSUE TITLE
ERROR: the following packages/stacks could not have their rosdep keys resolved to system dependencies:

### ISSUE THREAD

**Issue by Sprinzzzz** [mikepurvis/ros-install-osx#136]
Hello,

I am trying to integrate realsense D435i on Jetson Xavier following this tutorial [](https://github.com/JETSONHACKS/INSTALLrEALSENSE2rOStX), [](https://www.youtube.com/watch?v=-q3jGJgFZ7Q) . I ran into the following error with the command 

`./installRealSenseROS.sh trial_ws`

```
Making Intel ROS realsense
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
realsense2_camera: Cannot locate rosdep definition for [librealsense2]
./installRealSenseROS.sh: line 88: syntax error: unexpected end of file
```

I found this issue to be similar- [](https://github.com/mikepurvis/ros-install-osx/issues/9)

Could you please specify if this is the right usage? I tried with.
`rosdep install --from-paths'/home/nvidia/trial_ws/src/realsense' --ignore-src --rosdistro $ melodic -y --as-root pip:no --skip-keys="gazebo"`

Thank you in advance.

**Comment by mikepurvis** [comment]
This looks unrelated to OS X. Please see: http://wiki.ros.org/librealsense2 for RealSense setup.
