### ISSUE TITLE
Error building pcl_ros, glew not found

### ISSUE THREAD

**Issue by mahaarbo** [mikepurvis/ros-install-osx#16]
Whenever I try to run the script, it fails when trying to build pcl_ros. 
>CMake Error at /usr/local/share/pcl-1.8/PCLConfig.cmake:46 (message):
>  simulation is required but glew was not found
>Call Stack (most recent call first):
>  /usr/local/share/pcl-1.8/PCLConfig.cmake:645 (pcl_report_not_found)
>  /usr/local/share/pcl-1.8/PCLConfig.cmake:808 (find_external_library)
>  CMakeLists.txt:8 (find_package)

Tried first on Yosemite, and now on El Capitan to no avail. According to brew, glew is installed.

**Comment by anlif** [comment]
See #12

**Comment by mahaarbo** [comment]
The change to PCLConfig.cmake by @ahundt worked for me. Thanks.
