### ISSUE TITLE
Issue with Gazebo during compilation

### ISSUE THREAD

**Issue by lilouch** [mikepurvis/ros-install-osx#46]
Hi, I'm trying to install ROS on my OSX El Capitan 10.11.5  but without success.

I'm not able to compile perfectly Gazebo. I got this error : 
```
,/usr/local/lib -Wl,-rpath,/usr/local/Cellar/bullet/2.83.7/lib 
ld: library not found for -ltinyxml
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [gazebo/msgs/libgazebo_msgs.7.2.0.dylib] Error 1
make[1]: *** [gazebo/msgs/CMakeFiles/gazebo_msgs.dir/all] Error 2
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/osrf/homebrew-simulation/issues

ERROR: the following rosdeps failed to install
  homebrew: command [brew install gazebo7] failed
```

It seems that it is not able to find tinyxml. However I checked and It well installed.
Coud you please help me ?

Thank in advance,
Regards

**Comment by mikepurvis** [comment]
Please report this upstream: https://github.com/osrf/homebrew-simulation/issues

Helpful information you could include would be the outputs of `brew info tinyxml` and `brew list tinyxml`.
