### ISSUE TITLE
roslaunch image not found issue

### ISSUE THREAD

**Issue by MrAsimov** [mikepurvis/ros-install-osx#47]
When I am running the command "roslaunch" I get following issue. 

> ImportError: dlopen(/opt/ros/indigo/lib/python2.7/site-packages/tf2_py/_tf2.so, 2): Library not loaded: libtf2.dylib
>   Referenced from: /opt/ros/indigo/lib/python2.7/site-packages/tf2_py/_tf2.so
>   Reason: image not found

I get the feeling it's not importing it's dependencies properly. Is this really an issue?

**Comment by StealthAsimov** [comment]
I didn't get this issue when I compiled ROS indigo from scratch.
