### ISSUE TITLE
Time to update for interactive_markers?

### ISSUE THREAD

**Issue by kubark42** [mikepurvis/ros-install-osx#61]
The line https://github.com/mikepurvis/ros-install-osx/blob/265c2677a11a1196bc25edb26fa1b17d1f1dd113/install#L143 implies that that section is no longer necessary one a new interactive_markers release has been made.

Reading https://github.com/ros-visualization/interactive_markers/issues/31, it looks like this is the case. Am I understanding that correctly?

**Comment by mikepurvis** [comment]
Indeed, thanks!

**Comment by kubark42** [comment]
@mikepurvis, sure thing! Out of curiosity, since I've already curl'ed it, do I need to go and undo anything?

**Comment by mikepurvis** [comment]
No change is necessary.
