### ISSUE TITLE
Include macOS Sierra when checking for SIP

### ISSUE THREAD

**Issue by kubark42** [mikepurvis/ros-install-osx#65]
SIP is also present on macOS Sierra. https://github.com/mikepurvis/ros-install-osx/blob/77bf795d06930d3456b640c40b900c1dc892b70d/install#L169 checks for OSX 10.11, but not the latest 10.12. It might be appropriate to upgrade the check to look for anything >= 10.11.

**Comment by mikepurvis** [comment]
Sure, could you provide a PR for this please?

**Comment by kubark42** [comment]
Sure! I'm unfamiliar with bash, so I did what seemed appropriate. Hope it's helpful.
