### ISSUE TITLE
Incompatible pycurl version error while installing url grabber 

### ISSUE THREAD

**Issue by ashirsat** [mikepurvis/ros-install-osx#72]
Hi,

I am trying to install ros-indigo on my mac os sierra using the ors-install-osx script.

I am getting the following error
`ERROR: the following rosdeps failed to install
  pip: command [pip install -U urlgrabber] failed`

The details of the error are as under. It seems to call on a different version on pycurl than is installed through brew 

`ImportError: dlopen(/usr/local/lib/python2.7/site-packages/pycurl.so, 2): Library not loaded: libcurl.4.dylib
      Referenced from: /usr/local/lib/python2.7/site-packages/pycurl.so
      Reason: Incompatible library version: pycurl.so requires version 9.0.0 or later, but libcurl.4.dylib provides version 7.0.0`

I have also ran brew update and brew upgrade before beginning the installation.

Please let me know if there is a way I can resolve this.

 Thanks

**Comment by loganE** [comment]
@ashirsat Not sure if you found the solution, but running:

pip install pycurl

seemed to clear the issue for me.
