### ISSUE TITLE
Error: No available formula with the name "pyqt" 

### ISSUE THREAD

**Issue by mhhabdelwahab** [mikepurvis/ros-install-osx#75]
~/ros-install-osx/indigo_desktop_full_ws ~/ros-install-osx
Error: No available formula with the name "pyqt" 
executing command [brew install pyqt]
Error: No available formula with the name "pyqt" 
==> Searching for similarly named formulae...
This similarly named formula was found:
pyqt5 ✔
To install it, run:
  brew install pyqt5 ✔
==> Searching taps...
Error: No formulae found in taps.
ERROR: the following rosdeps failed to install
  homebrew: command [brew install pyqt] failed

Any Suggestions?

**Comment by BrutusTT** [comment]
pyqt is deprecated and broken with brew. the formular for it you can find in the boneyard.

You can try:
brew tap homebrew/boneyard
brew install pyqt

see https://github.com/Homebrew/homebrew-boneyard/blob/master/README.md

**Comment by mhhabdelwahab** [comment]
Thank you

**Comment by mikepurvis** [comment]
Please see #84 for ideas and updates around QT5.
