### ISSUE TITLE
rosmake won't find packages after install

### ISSUE THREAD

**Issue by nguillermin** [mikepurvis/ros-install-osx#8]
I get

    [ rosmake ] rosmake starting...                                                                                                                                                                             
    [ rosmake ] Packages requested are: ['lsd_slam']                                                                                                                                                            
    [ rosmake ] Logging to directory /Users/megablanc/.ros/rosmake/rosmake_output-20150813-205856                                                                                                               
    [ rosmake ] Expanded args ['lsd_slam'] to:
    []                                                                                                                                                               
    [ rosmake ] WARNING: The following args could not be parsed as stacks or packages: ['lsd_slam']                                                                                                             
    [ rosmake ] ERROR: No arguments could be parsed into valid package or stack names.   

After installing via the script.

Relevant info:

    echo $ROS_PACKAGE_PATH
    /opt/ros/indigo/share:/opt/ros/indigo/stacks

Not sure what the problem is here

    ls /opt/ros/indigo/share | grep "lsd_slam"
    lsd_slam

The stack.xml in lsd_slam:

    <stack>
      <description brief="lsd_slam">
    
    	Large-Scale Direct Monocular SLAM
    
      </description>
      <author>Maintained by Jakob Engel</author>
      <license>see http://vision.in.tum.de/lsdslam </license>
      <review status="unreviewed" notes="under active development"/>
      <url>http://vision.in.tum.de/lsdslam</url>
      <depend stack="ros" />
    
    </stack>

However, if I do `rosmake lsd_slam_core` it does work. Lsd_slam_core is one of the two packages in lsd_slam, like so:

    tree lsd_slam/ -L 2
    lsd_slam/
    ├── LICENSE
    ├── README.md
    ├── lsd_slam_core
    │   ├── CMakeLists.txt
    │   ├── Makefile
    │   ├── calib
    │   ├── cfg
    │   ├── cmake
    │   ├── manifest.xml
    │   ├── src
    │   └── thirdparty
    ├── lsd_slam_viewer
    │   ├── CMakeLists.txt
    │   ├── Makefile
    │   ├── bin
    │   ├── build
    │   ├── cfg
    │   ├── cmake
    │   ├── manifest.xml
    │   ├── msg
    │   ├── src
    │   └── thirdparty
    └── stack.xml

**Comment by mikepurvis** [comment]
I'm unsure what it is you're trying to do. Are you trying to install a rosbuild package alongside the rest of the base system, in `/opt/ros/indigo`? If so, that is definitely unsupported and I very much doubt it will work.

As far as building a rosbuild package from source in a rosbuild workspace, that should work, though it's been a long time since I did much with the rosbuild/rosmake tooling; you're going to be pretty much on your own with this path.

It looks like lsd_slam has a `catkin-mac` branch. Is there a reason you're not working from there?
