### ISSUE TITLE
rosdep keys unresolved

### ISSUE THREAD

**Issue by Dagrol** [mikepurvis/ros-install-osx#80]
I am getting the following error when I run the script:

ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
python_qt_binding: No definition of [python-qt-bindings] for OS [osx]
rviz: No definition of [libqt4-opengl-dev] for OS [osx]
gl_dependency: No definition of [python-qt-bindings-gl] for OS [osx]
qt_gui_cpp: No definition of [qt4-qmake] for OS [osx]
qt_gui: No definition of [python-qt-bindings] for OS [osx]
turtlesim: No definition of [libqt4] for OS [osx]

I tried to clean my rosdep and updated it but still no luck. Any ideas ?

**Comment by mattcurf** [comment]
I see the same errors above.  Mac OS X 10.12.4

**Comment by eaa3** [comment]
I appear to be having the exact same issue (OSX 10.11.6 El captain):

`ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
python_qt_binding: No definition of [python-qt-bindings] for OS [osx]
rviz: No definition of [libqt4-opengl-dev] for OS [osx]
gl_dependency: No definition of [python-qt-bindings-gl] for OS [osx]
webkit_dependency: No definition of [python-qt-bindings-webkit] for OS [osx]
qt_gui_cpp: No definition of [qt4-qmake] for OS [osx]
qt_gui: No definition of [python-qt-bindings] for OS [osx]
turtlesim: No definition of [libqt4] for OS [osx]`

**Comment by ashwini** [comment]
Same issue here, 10.12

**Comment by lujun723** [comment]
Mark, Same issue, 10.12

**Comment by fitsir** [comment]
Mark, same issue, 10.12.5

**Comment by ccckblaze** [comment]
Mark, Same issue, 10.12

**Comment by ashishraste** [comment]
Ran across the same issue, it has to do with Homebrew not supporting qt4 formula, as discussed here: https://github.com/ros/rosdistro/issues/14416

**Comment by mikepurvis** [comment]
Yes, the issue is with Homebrew no longer having qt4. The only reasonable path forward here is to migrate this project to qt5/Kinetic, which I haven't had the time to do.

Going to close this ticket for now in favour of #63.
