### ISSUE TITLE
ERROR: the following packages/stacks could not have their rosdep keys resolved to system dependencies:

### ISSUE THREAD

**Issue by lizixroy** [mikepurvis/ros-install-osx#83]
Hey guys,

On 10.12.6 (16G29) macOS Sierra, I am getting the following error while running the script:

ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
python_qt_binding: No definition of [python-qt-bindings] for OS [osx]
rviz: No definition of [libqt4-opengl-dev] for OS [osx]
gl_dependency: No definition of [python-qt-bindings-gl] for OS [osx]
webkit_dependency: No definition of [python-qt-bindings-webkit] for OS [osx]
qt_gui_cpp: No definition of [qt4-qmake] for OS [osx]
qt_gui: No definition of [python-qt-bindings] for OS [osx]
turtlesim: No definition of [libqt4] for OS [osx]

@mikepurvis  Any idea how to fix this?

Many thanks for your time.

Roy

**Comment by mikepurvis** [comment]
Please see the changes proposed in #84.
