### ISSUE TITLE
rosdep keys cannot be resolved to system dependencies

### ISSUE THREAD

**Issue by tingelst** [mikepurvis/ros-install-osx#9]
I get the following error messages during installation. The system is a late 2013 MacBook Pro 15 running Yosemite. I removed all traces of homebrew and pip before starting. Do you have any solution for this?

```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
collada_urdf: No definition of [pcre-dev] for OS [osx]
urdf: No definition of [pcre-dev] for OS [osx]
stage_ros: No definition of [fluid] for OS [osx]
stage: No definition of [libfltk-dev] for OS [osx]
```

**Comment by mikepurvis** [comment]
Those packages are definitely part of rosdep/osx/homebrew:

https://github.com/ros/rosdistro/blob/b8242094ec43dfa7c146e22496e60ed18f97be71/rosdep/osx-homebrew.yaml#L461
https://github.com/ros/rosdistro/blob/b8242094ec43dfa7c146e22496e60ed18f97be71/rosdep/osx-homebrew.yaml#L94
https://github.com/ros/rosdistro/blob/b8242094ec43dfa7c146e22496e60ed18f97be71/rosdep/osx-homebrew.yaml#L178

Maybe you got a bad rosdep clone or something? Consider:

```
rm -rf /etc/ros/rosdep
sudo rosdep init
rosdep update
```

And then try the rosdep line again:

    rosdep install --from-paths src --ignore-src --rosdistro ${ROS_DISTRO} -y --as-root pip:no --skip-keys="gazebo"

If it works correctly, create the install dir and run the build manually to avoid re-downloading everything:

https://github.com/mikepurvis/ros-install-osx/blob/6472e866699ced3522e9876cd2e0749fea658ba6/install#L150

**Comment by tingelst** [comment]
That was it. I had a non-empty `/etc/ros/rosdep` directory from a failed installation attempt some months ago. The rest of the installation process was successful after this fix.

Thanks for the feedback! I guess this one can be closed now.

**Comment by ihamieh** [comment]
I'm having a similar problem but i'm not sure how to solve it! 
I'm trying to install VLP16 to my ubuntu 16 with ROS kinetic but I also have Lego Loam installed and when i try the following, I get the error message! 

~/catkin_ws$ rosdep install --from-paths src --ignore-src --rosdistro=${ROS_DISTRO} -y
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
lego_loam: Cannot locate rosdep definition for [gtsam]

**Comment by arm3nyn** [comment]
> I'm having a similar problem but i'm not sure how to solve it!
> I'm trying to install VLP16 to my ubuntu 16 with ROS kinetic but I also have Lego Loam installed and when i try the following, I get the error message!
> 
> ~/catkin_ws$ rosdep install --from-paths src --ignore-src --rosdistro=${ROS_DISTRO} -y
> ERROR: the following packages/stacks could not have their rosdep keys resolved
> to system dependencies:
> lego_loam: Cannot locate rosdep definition for [gtsam]

same here
