### ISSUE TITLE
Linker error on image_publisher

### ISSUE THREAD

**Issue by eric1221bday** [mikepurvis/ros-install-osx#92]
So this is a very basic linker error on `image_publisher`. Essentially, `image_publisher`'s `CMakelists.txt` is missing both its `find_package(OpenCV REQUIRED)`, and `target_link_libraries(${PROJECT_NAME} ${catkin_LIBRARIES} ${OpenCV_LIBRARIES})`.

The bizarre thing is, I had managed a successful compilation not 5 hours prior on a different MacBook also running 10.13, with the only difference being that I had XCode installed instead of using XCode CLT, and clearly since the cmake file has not been edited for a long time this must have worked for everyone on Linux as well. I'm curious if anyone who does not have XCode installed on their Mac can try to replicate this linker failure.

EDIT: it looks like somebody already did a pull request on this exact issue, ros-perception/image_pipeline#304

**Comment by mikepurvis** [comment]
Patched in with 8c1bb1db0ab2b03f7218b82702e6921852f070e3.

Closing this ticket since the underlying issue is tracked with the upstream.
